Hero
Artekme/project-ScriptTailors pull request #2
Opened 2024-04-11 15:17 UTC by Plyampus

2024-04-11 18:35 UTC, AnnaSamtash approved these changes

2024-04-11 20:43 UTC, Artekme requested changes
1. You dont need to change style.css at all
2. No zny pictures/svg in your section, please remove instagram.svg and img/hero as well
Thank you

2024-04-13 16:24 UTC, Artekme approved these changes

2024-04-13 16:25 UTC, Artekme approved these changes

2024-04-13 16:25 UTC, merged